### PR TITLE
Migrate to PureScript 0.14

### PR DESCRIPTION
**Pull request by fsoikin**
This PR makes necessary changes for migrating to PureScript 0.14 and repoints `packages.dhall` to `psc-0.14.0` package set.

### CODE REVIEW

**Comment by paluh** [comment]
Hi @fsoikin,

Thank you very much for the PR. I'm also really sorry that it stays here for so long - I don't use _purs-0.14_ yet. I promise (😮) to do this merge during this weekend.

**Comment by fsoikin** [comment]
Not super urgent @paluh, we're just using my branch added as extra-dep right now. Still, would be nice to have everything nice and in the package set.

**Comment by paluh** [comment]
@fsoikin - sorry for a small delay. I hope I've done everything correctly - here is my _package-set_ PR with new version: https://github.com/purescript/package-sets/pull/907

Once again thanks!

**Comment by fsoikin** [comment]
Thank you very much!

**Pull request merged**
